# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'EasyBuy' do

  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'


  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EasyBuy

  target 'EasyBuy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'EasyBuyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EasyBuy-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EasyBuy-tvOS

  

end
